services:
  metamodels.attribute_translatedtablemulti.factory:
    class: MetaModels\AttributeTranslatedTableMultiBundle\Attribute\AttributeTypeFactory
    arguments:
      - "@database_connection"
    tags:
      - { name: metamodels.attribute_factory }

  MetaModels\AttributeTranslatedTableMultiBundle\Migration\ChangeTranslatedTableNameMigration:
    arguments:
      - '@database_connection'
    tags:
      - name: contao.migration
