services:
  metamodels.attribute_translatedtablemulti.factory:
    class: MetaModels\AttributeTranslatedTableMultiBundle\Attribute\AttributeTypeFactory
    arguments:
      - "@database_connection"
    tags:
      - { name: metamodels.attribute_factory }